import {
	feedImage1,
	feedImage2,
	feedImage3,
	feedImage4,
	feedImage5,
	member1,
	member2,
	member3,
	member4,
	member5,
	member6,
	member7,
	member8,
	member9,
	photo1,
	photo2,
	photo3,
	photo4,
	photo5,
	photo6,
	profile,
	shortcut1,
	shortcut2,
	shortcut3,
	shortcut4,
	status1,
	status2,
	status3,
	status4,
	status5,
} from '../../../public/images'

export const Members = [
	{ name: 'Maggie', pict: member1 },
	{ name: 'Alison', pict: member2 },
	{ name: 'Pelagie', pict: member3 },
	{ name: 'Giresse', pict: member4 },
	{ name: 'Patrick', pict: member5 },
	{ name: 'Clarisse', pict: member6 },
	{ name: 'David', pict: member7 },
	{ name: 'Erunice', pict: member8 },
	{ name: 'Cyril', pict: member9 },
]
export const Posts = [
	{
		name: 'Maggie',
        profile: profile,
		date: 'August 05, 2022',
		pict: member1,
		feed: feedImage1,
		text: 'Subscribe to <strong>socialbook</strong> my channel to watch more videos on website development and UI designs',
	},
	{
		name: 'Alison',
		profile: profile,
		date: 'August 24, 2022',
		pict: member2,
		feed: feedImage2,
		text: `Like and share this video with friends, tag <strong>socialbook</strong> facebook page on your post. Ask your doubts in the comments`,
	},
	{
		name: 'Pelagie',
		profile: profile,
		date: 'August 24, 2022',
		pict: member3,
		feed: feedImage3,
		text: `Like and share this video with friends, tag <strong>socialbook</strong> facebook page on your post. Ask your doubts in the comments`,
	},
	{
		name: 'Giresse',
		profile: profile,
		date: 'August 24, 2022',
		pict: member4,
		feed: feedImage4,
		text: `Like and share this video with friends, tag <strong>socialbook</strong> facebook page on your post. Ask your doubts in the comments`,
	},
	{
		name: 'Patrick',
		profile: profile,
		date: 'August 24, 2022',
		pict: member5,
		feed: feedImage5,
		text: `Like and share this video with friends, tag <strong>socialbook</strong> facebook page on your post. Ask your doubts in the comments`,
	},
	{
		name: 'Clarisse',
		profile: profile,
		date: 'August 24, 2022',
		pict: member6,
		feed: feedImage1,
		text: `Like and share this video with friends, tag <strong>socialbook</strong> facebook page on your post. Ask your doubts in the comments`,
	},
	{
		name: 'David',
		profile: profile,
		date: 'August 24, 2022',
		pict: member7,
		feed: feedImage2,
		text: `Like and share this video with friends, tag <strong>socialbook</strong> facebook page on your post. Ask your doubts in the comments`,
	},
	{
		name: 'Eunice',
		profile: profile,
		date: 'August 24, 2022',
		pict: member8,
		feed: feedImage3,
		text: `Like and share this video with friends, tag <strong>socialbook</strong> facebook page on your post. Ask your doubts in the comments`,
	},
	{
		name: 'Cyril',
		profile: profile,
		date: 'August 24, 2022',
		pict: member9,
		feed: feedImage4,
		text: `Like and share this video with friends, tag <strong>socialbook</strong> facebook page on your post. Ask your doubts in the comments`,
	},
]

export const Feeds = [
	{ thumbnail: feedImage1 },
	{ thumbnail: feedImage2 },
	{ thumbnail: feedImage3 },
	{ thumbnail: feedImage4 },
	{ thumbnail: feedImage5 },
]
export const Photos = [
	{ photo: photo1 },
	{ photo: photo2 },
	{ photo: photo3 },
	{ photo: photo4 },
	{ photo: photo5 },
	{ photo: photo6 },
]
export const Shortcuts = [
	{ shortcut: shortcut1 },
	{ shortcut: shortcut2 },
	{ shortcut: shortcut3 },
	{ shortcut: shortcut4 },
]
export const Status = [
	{ status: status1 },
	{ status: status2 },
	{ status: status3 },
	{ status: status4 },
	{ status: status5 },
]
